-- ========================================================
-- JobComm RTAF - Supabase Database Schema & Seed Data
-- ========================================================

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public.missions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'ทั่วไป',
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  start_time TEXT,
  end_time TEXT,
  location TEXT NOT NULL,
  description TEXT,
  assignee TEXT,
  status TEXT DEFAULT 'pending',
  priority TEXT DEFAULT 'normal',
  notes TEXT,
  attachment_url TEXT,
  attachment_name TEXT,
  attachment_type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.personnel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  role TEXT
);

-- 2. Disable Row Level Security (RLS) or allow public access for JobComm API
ALTER TABLE public.missions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.personnel DISABLE ROW LEVEL SECURITY;

-- 3. Seed Default Categories
INSERT INTO public.categories (name) VALUES
  ('ประชุม'),
  ('ซ่อมบำรุง'),
  ('ตรวจเช็คระบบ'),
  ('วางสายสัญญาณ'),
  ('วิทยุสื่อสาร'),
  ('ภารกิจพิเศษ'),
  ('ฝึกอบรม'),
  ('สื่อสารสนับสนุน')
ON CONFLICT (name) DO NOTHING;

-- 4. Seed Default Locations
INSERT INTO public.locations (name) VALUES
  ('ห้องประชุม บก.อย. 1'),
  ('ห้องประชุม บก.อย. 2'),
  ('ศูนย์ปฏิบัติการสื่อสาร อย.'),
  ('อาคารฝ่ายการสื่อสาร'),
  ('เสาส่งสัญญาณวิทยุสื่อสาร อย.'),
  ('ลานจอดอากาศยาน กองบิน 6'),
  ('สนามฝึกทางยุทธวิธี อย.'),
  ('ห้องสื่อสารเฉพาะกิจ')
ON CONFLICT (name) DO NOTHING;

-- 5. Seed Default Personnel
INSERT INTO public.personnel (name, role) VALUES
  ('น.ต. สุรชัย ช่างสื่อสาร', 'หน.แผนกสื่อสาร'),
  ('ร.อ. เกียรติศักดิ์ พลสื่อสาร', 'รอง หน.แผนก'),
  ('ร.ท. วรพงษ์ นายทหารวิทยุ', 'นายทหารวิทยุสื่อสาร'),
  ('พ.อ.อ. ธนกฤต ช่างสายสัญญาณ', 'เจ้าหน้าที่โครงข่าย'),
  ('จ.ส.อ. สมเกียรติ พลสื่อสาร', 'เจ้าหน้าที่สื่อสาร'),
  ('จ.ส.อ. วินัย ช่างวิทยุ', 'ช่างซ่อมบำรุงวิทยุ'),
  ('ส.อ. อนุชา ช่างเทคนิค', 'ช่างเทคนิคคอมพิวเตอร์'),
  ('ส.ท. ปฏิบัติการ เวรวิทยุ', 'เจ้าหน้าที่ประจำเวร')
ON CONFLICT (name) DO NOTHING;

-- 6. Create Storage Bucket for Attachments (if not exists)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('attachments', 'attachments', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policy to allow public uploads & downloads in attachments bucket
CREATE POLICY "Public Access" ON storage.objects FOR ALL USING (bucket_id = 'attachments') WITH CHECK (bucket_id = 'attachments');
